// @flow

import * as React from "react";

import type { Option } from "./types";
import Select from "./Select";

type Props = {|
  id?: string,
  onChange?: (SyntheticEvent<HTMLSelectElement>) => void,
  value: string,
|};

export default (props: Props) => (
  <Select id={props.id} onChange={props.onChange} value={props.value}>
    {countries.map(country => (
      <option key={country.value} value={country.value}>
        {country.label}
      </option>
    ))}
  </Select>
);

const countries: Option[] = [
  { value: "", label: "..." },
  { value: "Afghanistan", label: "Afghanistan" },
  { value: "Ägypten", label: "Ägypten" },
  { value: "Aland", label: "Aland" },
  { value: "Albanien", label: "Albanien" },
  { value: "Algerien", label: "Algerien" },
  { value: "Amerikanisch", label: "Amerikanisch" },
  {
    value: "Amerikanische Jungferninseln",
    label: "Amerikanische Jungferninseln",
  },
  { value: "Andorra", label: "Andorra" },
  { value: "Angola", label: "Angola" },
  { value: "Anguilla", label: "Anguilla" },
  { value: "Antarktis", label: "Antarktis" },
  { value: "Antigua und Barbuda", label: "Antigua und Barbuda" },
  { value: "Äquatorialguinea, Republik", label: "Äquatorialguinea, Republik" },
  { value: "Argentinien", label: "Argentinien" },
  { value: "Armenien", label: "Armenien" },
  { value: "Aruba", label: "Aruba" },
  { value: "Ascension", label: "Ascension" },
  { value: "Aserbaidschan", label: "Aserbaidschan" },
  { value: "Äthiopien", label: "Äthiopien" },
  { value: "Australien", label: "Australien" },
  { value: "Bahamas", label: "Bahamas" },
  { value: "Bahrain", label: "Bahrain" },
  { value: "Bangladesch", label: "Bangladesch" },
  { value: "Barbados", label: "Barbados" },
  { value: "Belgien", label: "Belgien" },
  { value: "Belize", label: "Belize" },
  { value: "Benin", label: "Benin" },
  { value: "Bermuda", label: "Bermuda" },
  { value: "Bhutan", label: "Bhutan" },
  { value: "Bolivien", label: "Bolivien" },
  { value: "Bosnien und Herzegowina", label: "Bosnien und Herzegowina" },
  { value: "Botswana", label: "Botswana" },
  { value: "Bouvetinsel", label: "Bouvetinsel" },
  { value: "Brasilien", label: "Brasilien" },
  { value: "Britische Jungferninseln", label: "Britische Jungferninseln" },
  {
    value: "Britisches Territorium im Indischen Ozean",
    label: "Britisches Territorium im Indischen Ozean",
  },
  { value: "Brunei", label: "Brunei" },
  { value: "Bulgarien", label: "Bulgarien" },
  { value: "Burkina Faso", label: "Burkina Faso" },
  { value: "Burundi", label: "Burundi" },
  { value: "Chile", label: "Chile" },
  { value: "China, Volksrepublik", label: "China, Volksrepublik" },
  { value: "Cookinseln", label: "Cookinseln" },
  { value: "Costa Rica", label: "Costa Rica" },
  { value: "Cote d'Ivoire", label: "Cote d'Ivoire" },
  { value: "Dänemark", label: "Dänemark" },
  { value: "Deutschland", label: "Deutschland" },
  {
    value: "Die Kronkolonie St. Helena und Nebengebiete",
    label: "Die Kronkolonie St. Helena und Nebengebiete",
  },
  { value: "Diego Garcia", label: "Diego Garcia" },
  { value: "Dominica", label: "Dominica" },
  { value: "Dominikanische Republik", label: "Dominikanische Republik" },
  { value: "Dschibuti", label: "Dschibuti" },
  { value: "Ecuador", label: "Ecuador" },
  { value: "El Salvador", label: "El Salvador" },
  { value: "Eritrea", label: "Eritrea" },
  { value: "Estland", label: "Estland" },
  { value: "Europäische Union", label: "Europäische Union" },
  { value: "Falklandinseln", label: "Falklandinseln" },
  { value: "Färöer", label: "Färöer" },
  { value: "Fidschi", label: "Fidschi" },
  { value: "Finnland", label: "Finnland" },
  { value: "Frankreich", label: "Frankreich" },
  { value: "Französisch-Guayana", label: "Französisch-Guayana" },
  { value: "Französisch-Polynesien", label: "Französisch-Polynesien" },
  {
    value: "Französische Süd- und Antarktisgebiete",
    label: "Französische Süd- und Antarktisgebiete",
  },
  { value: "Gabun", label: "Gabun" },
  { value: "Gambia", label: "Gambia" },
  { value: "Georgien", label: "Georgien" },
  { value: "Ghana, Republik", label: "Ghana, Republik" },
  { value: "Gibraltar", label: "Gibraltar" },
  { value: "Grenada", label: "Grenada" },
  { value: "Griechenland", label: "Griechenland" },
  { value: "Grönland", label: "Grönland" },
  { value: "Guadeloupe", label: "Guadeloupe" },
  { value: "Guam", label: "Guam" },
  { value: "Guatemala", label: "Guatemala" },
  { value: "Guernsey, Vogtei", label: "Guernsey, Vogtei" },
  { value: "Guinea, Republik", label: "Guinea, Republik" },
  { value: "Guinea-Bissau, Republik", label: "Guinea-Bissau, Republik" },
  { value: "Guyana", label: "Guyana" },
  { value: "Haiti", label: "Haiti" },
  { value: "Heard und McDonaldinseln", label: "Heard und McDonaldinseln" },
  { value: "Honduras", label: "Honduras" },
  { value: "Hongkong", label: "Hongkong" },
  { value: "Indien", label: "Indien" },
  { value: "Indonesien", label: "Indonesien" },
  { value: "Insel Man", label: "Insel Man" },
  { value: "Irak", label: "Irak" },
  { value: "Iran", label: "Iran" },
  { value: "Irland, Republik", label: "Irland, Republik" },
  { value: "Island", label: "Island" },
  { value: "Israel", label: "Israel" },
  { value: "Italien", label: "Italien" },
  { value: "Jamaika", label: "Jamaika" },
  { value: "Japan", label: "Japan" },
  { value: "Jemen", label: "Jemen" },
  { value: "Jersey", label: "Jersey" },
  { value: "Jordanien", label: "Jordanien" },
  { value: "Kaimaninseln", label: "Kaimaninseln" },
  { value: "Kambodscha", label: "Kambodscha" },
  { value: "Kamerun", label: "Kamerun" },
  { value: "Kanada", label: "Kanada" },
  { value: "Kanarische Inseln", label: "Kanarische Inseln" },
  { value: "Kap Verde, Republik", label: "Kap Verde, Republik" },
  { value: "Kasachstan", label: "Kasachstan" },
  { value: "Katar", label: "Katar" },
  { value: "Kenia", label: "Kenia" },
  { value: "Kirgisistan", label: "Kirgisistan" },
  { value: "Kiribati", label: "Kiribati" },
  { value: "Kokosinseln", label: "Kokosinseln" },
  { value: "Kolumbien", label: "Kolumbien" },
  { value: "Komoren", label: "Komoren" },
  {
    value: "Kongo, Demokratische Republik",
    label: "Kongo, Demokratische Republik",
  },
  { value: "Kongo, Republik", label: "Kongo, Republik" },
  {
    value: "Korea, Demokratische Volkrepublik",
    label: "Korea, Demokratische Volkrepublik",
  },
  { value: "Korea, Republik", label: "Korea, Republik" },
  { value: "Kroatien", label: "Kroatien" },
  { value: "Kuba", label: "Kuba" },
  { value: "Kuwait", label: "Kuwait" },
  { value: "Laos", label: "Laos" },
  { value: "Lesotho", label: "Lesotho" },
  { value: "Lettland", label: "Lettland" },
  { value: "Libanon", label: "Libanon" },
  { value: "Liberia, Republik", label: "Liberia, Republik" },
  { value: "Libyen", label: "Libyen" },
  { value: "Liechtenstein, Fürstentum", label: "Liechtenstein, Fürstentum" },
  { value: "Litauen", label: "Litauen" },
  { value: "Luxemburg", label: "Luxemburg" },
  { value: "Macao", label: "Macao" },
  { value: "Madagaskar, Republik", label: "Madagaskar, Republik" },
  { value: "Malawi, Republik", label: "Malawi, Republik" },
  { value: "Malaysia", label: "Malaysia" },
  { value: "Malediven", label: "Malediven" },
  { value: "Mali, Republik", label: "Mali, Republik" },
  { value: "Malta", label: "Malta" },
  { value: "Marokko", label: "Marokko" },
  { value: "Marshallinseln", label: "Marshallinseln" },
  { value: "Martinique", label: "Martinique" },
  { value: "Mauretanien", label: "Mauretanien" },
  { value: "Mauritius, Republik", label: "Mauritius, Republik" },
  { value: "Mayotte", label: "Mayotte" },
  { value: "Mazedonien", label: "Mazedonien" },
  { value: "Mexiko", label: "Mexiko" },
  {
    value: "Mikronesien, Föderierte Staaten von",
    label: "Mikronesien, Föderierte Staaten von",
  },
  { value: "Moldawien", label: "Moldawien" },
  { value: "Monaco", label: "Monaco" },
  { value: "Mongolei", label: "Mongolei" },
  { value: "Montserrat", label: "Montserrat" },
  { value: "Mosambik", label: "Mosambik" },
  { value: "Myanmar", label: "Myanmar" },
  { value: "Namibia, Republik", label: "Namibia, Republik" },
  { value: "Nauru", label: "Nauru" },
  { value: "Nepal", label: "Nepal" },
  { value: "Neukaledonien", label: "Neukaledonien" },
  { value: "Neuseeland", label: "Neuseeland" },
  { value: "Neutrale Zone (Irak)", label: "Neutrale Zone (Irak)" },
  { value: "Nicaragua", label: "Nicaragua" },
  { value: "Niederlande", label: "Niederlande" },
  { value: "Niederländische Antillen", label: "Niederländische Antillen" },
  { value: "Niger", label: "Niger" },
  { value: "Nigeria", label: "Nigeria" },
  { value: "Niue", label: "Niue" },
  { value: "Nördliche Marianen", label: "Nördliche Marianen" },
  { value: "Norfolkinsel", label: "Norfolkinsel" },
  { value: "Norwegen", label: "Norwegen" },
  { value: "Oman", label: "Oman" },
  { value: "Österreich", label: "Österreich" },
  { value: "Pakistan", label: "Pakistan" },
  {
    value: "Palästinensische Autonomiegebiete",
    label: "Palästinensische Autonomiegebiete",
  },
  { value: "Palau", label: "Palau" },
  { value: "Panama", label: "Panama" },
  { value: "Papua-Neuguinea", label: "Papua-Neuguinea" },
  { value: "Paraguay", label: "Paraguay" },
  { value: "Peru", label: "Peru" },
  { value: "Philippinen", label: "Philippinen" },
  { value: "Pitcairninseln", label: "Pitcairninseln" },
  { value: "Polen", label: "Polen" },
  { value: "Portugal", label: "Portugal" },
  { value: "Puerto Rico", label: "Puerto Rico" },
  { value: "Réunion", label: "Réunion" },
  { value: "Ruanda, Republik", label: "Ruanda, Republik" },
  { value: "Rumänien", label: "Rumänien" },
  { value: "Russische Föderation", label: "Russische Föderation" },
  { value: "Salomonen", label: "Salomonen" },
  { value: "Sambia, Republik", label: "Sambia, Republik" },
  { value: "Samoa", label: "Samoa" },
  { value: "San Marino", label: "San Marino" },
  { value: "São Tomé und Príncipe", label: "São Tomé und Príncipe" },
  { value: "Saudi-Arabien, Königreich", label: "Saudi-Arabien, Königreich" },
  { value: "Schweden", label: "Schweden" },
  { value: "Schweiz", label: "Schweiz" },
  { value: "Senegal", label: "Senegal" },
  { value: "Serbien und Montenegro", label: "Serbien und Montenegro" },
  { value: "Seychellen, Republik der", label: "Seychellen, Republik der" },
  { value: "Sierra Leone, Republik", label: "Sierra Leone, Republik" },
  { value: "Simbabwe, Republik", label: "Simbabwe, Republik" },
  { value: "Singapur", label: "Singapur" },
  { value: "Slowakei", label: "Slowakei" },
  { value: "Slowenien", label: "Slowenien" },
  {
    value: "Somalia, Demokratische Republik",
    label: "Somalia, Demokratische Republik",
  },
  { value: "Spanien", label: "Spanien" },
  { value: "Sri Lanka", label: "Sri Lanka" },
  { value: "St. Kitts und Nevis", label: "St. Kitts und Nevis" },
  { value: "St. Lucia", label: "St. Lucia" },
  { value: "St. Pierre und Miquelon", label: "St. Pierre und Miquelon" },
  {
    value: "St. Vincent und die Grenadinen (GB)",
    label: "St. Vincent und die Grenadinen (GB)",
  },
  { value: "Südafrika, Republik", label: "Südafrika, Republik" },
  { value: "Sudan", label: "Sudan" },
  {
    value: "Südgeorgien und die Südlichen Sandwichinseln",
    label: "Südgeorgien und die Südlichen Sandwichinseln",
  },
  { value: "Suriname", label: "Suriname" },
  { value: "Svalbard und Jan Mayen", label: "Svalbard und Jan Mayen" },
  { value: "Swasiland", label: "Swasiland" },
  { value: "Syrien", label: "Syrien" },
  { value: "Tadschikistan", label: "Tadschikistan" },
  { value: "Taiwan", label: "Taiwan" },
  {
    value: "Tansania, Vereinigte Republik",
    label: "Tansania, Vereinigte Republik",
  },
  { value: "Thailand", label: "Thailand" },
  {
    value: "Timor-Leste, Demokratische Republik",
    label: "Timor-Leste, Demokratische Republik",
  },
  { value: "Togo, Republik", label: "Togo, Republik" },
  { value: "Tokelau", label: "Tokelau" },
  { value: "Tonga", label: "Tonga" },
  { value: "Trinidad und Tobago", label: "Trinidad und Tobago" },
  { value: "Tristan da Cunha", label: "Tristan da Cunha" },
  { value: "Tschad, Republik", label: "Tschad, Republik" },
  { value: "Tschechische Republik", label: "Tschechische Republik" },
  { value: "Tunesien", label: "Tunesien" },
  { value: "Türkei", label: "Türkei" },
  { value: "Turkmenistan", label: "Turkmenistan" },
  { value: "Turks- und Caicosinseln", label: "Turks- und Caicosinseln" },
  { value: "Tuvalu", label: "Tuvalu" },
  { value: "Uganda, Republik", label: "Uganda, Republik" },
  { value: "Ukraine", label: "Ukraine" },
  {
    value: "Union der Sozialistischen Sowjetrepubliken",
    label: "Union der Sozialistischen Sowjetrepubliken",
  },
  { value: "Uruguay", label: "Uruguay" },
  { value: "Usbekistan", label: "Usbekistan" },
  { value: "Vanuatu", label: "Vanuatu" },
  { value: "Vatikanstadt", label: "Vatikanstadt" },
  { value: "Venezuela", label: "Venezuela" },
  {
    value: "Vereinigte Arabische Emirate",
    label: "Vereinigte Arabische Emirate",
  },
  {
    value: "Vereinigte Staaten von Amerika",
    label: "Vereinigte Staaten von Amerika",
  },
  {
    value: "Vereinigtes Königreich von Großbritannien und Nordirland",
    label: "Vereinigtes Königreich von Großbritannien und Nordirland",
  },
  { value: "Vietnam", label: "Vietnam" },
  { value: "Wallis und Futuna", label: "Wallis und Futuna" },
  { value: "Weihnachtsinsel", label: "Weihnachtsinsel" },
  { value: "Weißrussland", label: "Weißrussland" },
  { value: "Westsahara", label: "Westsahara" },
  {
    value: "Zentralafrikanische Republik",
    label: "Zentralafrikanische Republik",
  },
  { value: "Zypern, Republik", label: "Zypern, Republik" },
  { value: "Ungarn", label: "Ungarn" },
  { value: "Montenegro", label: "Montenegro" },
  { value: "Kosovo", label: "Kosovo" },
];
