// @flow

import Highlighter from "react-highlight-words";
import type { SelectOption } from "react-select";
import { Creatable } from "react-select";
import * as React from "react";

type Props = {|
  forceInvalid?: boolean,
  id?: string,
  onChange?: (SyntheticEvent<HTMLSelectElement>) => void,
  value: string,
|};

export default class OrganizationSelect extends React.Component<Props, {}> {
  inputValue: string;

  constructor() {
    super();
    this.inputValue = "";
  }

  renderOption = (option: SelectOption) => (
    <Highlighter
      highlightClassName="highlight"
      searchWords={[this.inputValue]}
      textToHighlight={option.label}
    />
  );

  render(): React.Node {
    return (
      <Creatable
        className={this.props.forceInvalid ? "invalid" : ""}
        clearable={false}
        id={this.props.id}
        onChange={this.props.onChange}
        onInputChange={inputValue => (this.inputValue = inputValue)}
        optionRenderer={this.renderOption}
        options={organizations}
        promptTextCreator={l => l + " neu hinzufügen..."}
        value={this.props.value}
      />
    );
  }
}

const organizations = [
  { value: "3M Deutschland GmbH", label: "3M Deutschland GmbH" },
  { value: "3SOFT GmbH", label: "3SOFT GmbH" },
  { value: "Aareal Bank AG", label: "Aareal Bank AG" },
  { value: "ABAS Software AG", label: "ABAS Software AG" },
  { value: "ABB AG", label: "ABB AG" },
  { value: "ABIT AG", label: "ABIT AG" },
  { value: "ABN-AMRO Bank N.V", label: "ABN-AMRO Bank N.V" },
  { value: "ABS Team GmbH", label: "ABS Team GmbH" },
  { value: "Accenture", label: "Accenture" },
  { value: "access AG", label: "access AG" },
  { value: "ADAC e.V.", label: "ADAC e.V." },
  {
    value: "Adecco Personaldienstleistungen GmbH",
    label: "Adecco Personaldienstleistungen GmbH",
  },
  {
    value: "adevis Personaldienstleistungen GmbH & Co. KG",
    label: "adevis Personaldienstleistungen GmbH & Co. KG",
  },
  { value: "adidas-Salomon AG", label: "adidas-Salomon AG" },
  { value: "adsano e.K.", label: "adsano e.K." },
  { value: "AIR LIQUIDE GmbH", label: "AIR LIQUIDE GmbH" },
  { value: "Airbus Deutschland GmbH", label: "Airbus Deutschland GmbH" },
  { value: "akf bank GmbH & Co KG", label: "akf bank GmbH & Co KG" },
  { value: "Akzo Nobel GmbH", label: "Akzo Nobel GmbH" },
  {
    value: "Alcan Packaging Singen GmbH",
    label: "Alcan Packaging Singen GmbH",
  },
  { value: "Alcanet Deutschland GmbH", label: "Alcanet Deutschland GmbH" },
  {
    value: "Alcatel-Lucent Deutschland AG",
    label: "Alcatel-Lucent Deutschland AG",
  },
  {
    value: "ALDI Einkauf GmbH & Co. oHG - Unternehmensgruppe Nord",
    label: "ALDI Einkauf GmbH & Co. oHG - Unternehmensgruppe Nord",
  },
  { value: "Allbecon AG", label: "Allbecon AG" },
  { value: "Allianz AG", label: "Allianz AG" },
  {
    value: "ALPHA Business Solutions AG",
    label: "ALPHA Business Solutions AG",
  },
  { value: "Alpha Management GmbH", label: "Alpha Management GmbH" },
  { value: "Alphaform AG", label: "Alphaform AG" },
  { value: "Alstom Power AG", label: "Alstom Power AG" },
  { value: "ALTANA AG", label: "ALTANA AG" },
  { value: "ALTANA Chemie AG", label: "ALTANA Chemie AG" },
  { value: "ALTANA Pharma AG", label: "ALTANA Pharma AG" },
  { value: "Altran Deutschland GmbH", label: "Altran Deutschland GmbH" },
  { value: "Amazon.de", label: "Amazon.de" },
  {
    value: "AMD Saxony LLC & Co. KG & AMD Fab 36 LLC & Co. KG",
    label: "AMD Saxony LLC & Co. KG & AMD Fab 36 LLC & Co. KG",
  },
  { value: "AMTC GmbH & Co. KG", label: "AMTC GmbH & Co. KG" },
  { value: "antwerpes ag", label: "antwerpes ag" },
  { value: "AOK Bundesverband", label: "AOK Bundesverband" },
  {
    value: "AOL Deutschland GmbH & Co. KG",
    label: "AOL Deutschland GmbH & Co. KG",
  },
  { value: "Apple Computer, Inc.", label: "Apple Computer, Inc." },
  { value: "arag Gruppe", label: "arag Gruppe" },
  { value: "Aral AG", label: "Aral AG" },
  { value: "Arcor AG & Co.KG", label: "Arcor AG & Co.KG" },
  {
    value: "VON ARDENNE Anlagentechnik GmbH",
    label: "VON ARDENNE Anlagentechnik GmbH",
  },
  { value: "ARDEX GmbH", label: "ARDEX GmbH" },
  { value: "Armstrong DLW AG", label: "Armstrong DLW AG" },
  { value: "Arthur D. Little GmbH", label: "Arthur D. Little GmbH" },
  { value: "ArtVoice Gruppe", label: "ArtVoice Gruppe" },
  { value: "arvato AG", label: "arvato AG" },
  {
    value: "A.S.I. Wirtschaftsberatung AG",
    label: "A.S.I. Wirtschaftsberatung AG",
  },
  { value: "A.T. Kearney GmbH", label: "A.T. Kearney GmbH" },
  { value: "Atos Origin GmbH", label: "Atos Origin GmbH" },
  { value: "Audi AG", label: "Audi AG" },
  { value: "AVISO GmbH", label: "AVISO GmbH" },
  { value: "AVM GmbH", label: "AVM GmbH" },
  { value: "AXA Konzern AG", label: "AXA Konzern AG" },
  { value: "Axel Springer AG", label: "Axel Springer AG" },
  { value: "Bahlsen GmbH & Co. KG", label: "Bahlsen GmbH & Co. KG" },
  {
    value: "Bain & Company Germany, Inc.",
    label: "Bain & Company Germany, Inc.",
  },
  { value: "Baker Hughes", label: "Baker Hughes" },
  { value: "Balda AG", label: "Balda AG" },
  { value: "Balluff GmbH", label: "Balluff GmbH" },
  { value: "Bankgesellschaft Berlin AG", label: "Bankgesellschaft Berlin AG" },
  { value: "Bankhaus L KG", label: "Bankhaus L KG" },
  { value: "Barclays Bank PLC", label: "Barclays Bank PLC" },
  { value: "Barmenia Versicherungen", label: "Barmenia Versicherungen" },
  { value: "Barmer Ersatzkasse", label: "Barmer Ersatzkasse" },
  { value: "Barten & Barten", label: "Barten & Barten" },
  { value: "BASF AG", label: "BASF AG" },
  { value: "Basler AG", label: "Basler AG" },
  {
    value: "British American Tobacco (Germany) GmbH",
    label: "British American Tobacco (Germany) GmbH",
  },
  { value: "Heinrich Bauer Verlag", label: "Heinrich Bauer Verlag" },
  { value: "Bayer AG", label: "Bayer AG" },
  { value: "Bayerische Landesbank", label: "Bayerische Landesbank" },
  { value: "Bayerischer Rundfunk", label: "Bayerischer Rundfunk" },
  { value: "BBDO Germany", label: "BBDO Germany" },
  { value: "BearingPoint GmbH", label: "BearingPoint GmbH" },
  { value: "Behr GmbH & Co. KG", label: "Behr GmbH & Co. KG" },
  { value: "Beiersdorf AG", label: "Beiersdorf AG" },
  { value: "Benteler International AG", label: "Benteler International AG" },
  {
    value: "Berliner Glas KGaA Herbert Kubatz GmbH & Co.",
    label: "Berliner Glas KGaA Herbert Kubatz GmbH & Co.",
  },
  {
    value: "berolina Schriftbild GmbH & Co. KG",
    label: "berolina Schriftbild GmbH & Co. KG",
  },
  { value: "Bertelsmann AG", label: "Bertelsmann AG" },
  { value: "Bertrandt AG", label: "Bertrandt AG" },
  { value: "Berufsstart Aktuell", label: "Berufsstart Aktuell" },
  {
    value: "BEUMER Maschinenfabrik GmbH & Co. KG",
    label: "BEUMER Maschinenfabrik GmbH & Co. KG",
  },
  {
    value: "Bewag Aktiengesellschaft & Co. KG",
    label: "Bewag Aktiengesellschaft & Co. KG",
  },
  { value: "BG-PHOENICS GMBH", label: "BG-PHOENICS GMBH" },
  {
    value: "BHF-BANK Aktiengesellschaft",
    label: "BHF-BANK Aktiengesellschaft",
  },
  { value: "BHW Holding AG", label: "BHW Holding AG" },
  { value: "Bilfinger Berger AG", label: "Bilfinger Berger AG" },
  { value: "biodata ANALYTIK GmbH", label: "biodata ANALYTIK GmbH" },
  { value: "BIOTRONIK GmbH & Co. KG", label: "BIOTRONIK GmbH & Co. KG" },
  {
    value: "bluequest Visual Communication",
    label: "bluequest Visual Communication",
  },
  { value: "Blume 2000", label: "Blume 2000" },
  { value: "BMW AG", label: "BMW AG" },
  { value: "BNP Paribas Lease Group SA", label: "BNP Paribas Lease Group SA" },
  { value: "BNP Paribas Niederlassung", label: "BNP Paribas Niederlassung" },
  { value: "Otto Bock HealthCare GmbH", label: "Otto Bock HealthCare GmbH" },
  {
    value: "Bodensee Standort Marketing GmbH",
    label: "Bodensee Standort Marketing GmbH",
  },
  {
    value: "Boehringer Ingelheim Pharma GmbH & Co. KG",
    label: "Boehringer Ingelheim Pharma GmbH & Co. KG",
  },
  {
    value: "bofrost*Dienstleistungs GmbH & Co. KG",
    label: "bofrost*Dienstleistungs GmbH & Co. KG",
  },
  {
    value: "Bombardier Transportation GmbH",
    label: "Bombardier Transportation GmbH",
  },
  {
    value: "bonprix Handelsgesellschaft mbH",
    label: "bonprix Handelsgesellschaft mbH",
  },
  { value: "Booz Allen Hamilton GmbH", label: "Booz Allen Hamilton GmbH" },
  { value: "BORGWARE GmbH", label: "BORGWARE GmbH" },
  { value: "Borland GmbH", label: "Borland GmbH" },
  { value: "Robert Bosch GmbH", label: "Robert Bosch GmbH" },
  { value: "Bosch Rexroth AG", label: "Bosch Rexroth AG" },
  { value: "HUGO BOSS AG", label: "HUGO BOSS AG" },
  {
    value: "The Boston Consulting Group GmbH",
    label: "The Boston Consulting Group GmbH",
  },
  { value: "Deutsche BP AG", label: "Deutsche BP AG" },
  { value: "BPW Bergische Achsen KG", label: "BPW Bergische Achsen KG" },
  { value: "Brainlab AG", label: "Brainlab AG" },
  { value: "Brauerei Beck GmbH & Co KG", label: "Brauerei Beck GmbH & Co KG" },
  {
    value: "Brenntag Holding GmbH & Co. KG",
    label: "Brenntag Holding GmbH & Co. KG",
  },
  { value: "BRITA GmbH", label: "BRITA GmbH" },
  {
    value: "Brose Fahrzeugteile GmbH & Co. Kommanditgesellschaft",
    label: "Brose Fahrzeugteile GmbH & Co. Kommanditgesellschaft",
  },
  { value: "Brunel GmbH", label: "Brunel GmbH" },
  { value: "Bundesgrenzschutz", label: "Bundesgrenzschutz" },
  { value: "Bundesnachrichtendienst", label: "Bundesnachrichtendienst" },
  { value: "Bundeswehr", label: "Bundeswehr" },
  {
    value: "Hubert Burda Media  Holding GmbH & Co. Kommanditgesellschaft",
    label: "Hubert Burda Media  Holding GmbH & Co. Kommanditgesellschaft",
  },
  { value: "BURGER KING GmbH", label: "BURGER KING GmbH" },
  {
    value: "BW-Bildung und Wissen Verlag und Software GmbH",
    label: "BW-Bildung und Wissen Verlag und Software GmbH",
  },
  { value: "Stiftung caesar", label: "Stiftung caesar" },
  { value: "C GmbH & Co. KG", label: "C GmbH & Co. KG" },
  { value: "C Verlag GmbH", label: "C Verlag GmbH" },
  { value: "Cannon Deutschland GmbH", label: "Cannon Deutschland GmbH" },
  { value: "Canon Deutschland GmbH", label: "Canon Deutschland GmbH" },
  { value: "Capgemini Deutschland GmbH", label: "Capgemini Deutschland GmbH" },
  { value: "CAS Software AG", label: "CAS Software AG" },
  {
    value: "CDV Software Entertainment AG",
    label: "CDV Software Entertainment AG",
  },
  { value: "Cell Consulting AG", label: "Cell Consulting AG" },
  { value: "CeWe Color AG & Co. OHG", label: "CeWe Color AG & Co. OHG" },
  {
    value: "CG Car-Garantie Versicherungs-Aktiengesellschaft",
    label: "CG Car-Garantie Versicherungs-Aktiengesellschaft",
  },
  { value: "CGI", label: "CGI" },
  { value: "CHEP Deutschland GmbH", label: "CHEP Deutschland GmbH" },
  {
    value: "Chubb Insurance Company of Europe, S.A.",
    label: "Chubb Insurance Company of Europe, S.A.",
  },
  {
    value: "Cine Plus Media Service GmbH & Co. KG",
    label: "Cine Plus Media Service GmbH & Co. KG",
  },
  {
    value: "CinemaxX Cinema GmbH & Co KG",
    label: "CinemaxX Cinema GmbH & Co KG",
  },
  { value: "CISCO SYSTEMS", label: "CISCO SYSTEMS" },
  { value: "Clariant GmbH", label: "Clariant GmbH" },
  { value: "Clifford Chance", label: "Clifford Chance" },
  { value: "Coca-Cola GmbH", label: "Coca-Cola GmbH" },
  {
    value: "Cognis Deutschland GmbH & Co. KG",
    label: "Cognis Deutschland GmbH & Co. KG",
  },
  { value: "Commerzbank AG", label: "Commerzbank AG" },
  {
    value: "COMPAGNIE DE SAINT-GOBAIN Zweigniederlassung Deutschland",
    label: "COMPAGNIE DE SAINT-GOBAIN Zweigniederlassung Deutschland",
  },
  { value: "COMPO GmbH & Co. KG", label: "COMPO GmbH & Co. KG" },
  { value: "Computacenter AG & Co. oHG", label: "Computacenter AG & Co. oHG" },
  {
    value: "Endress + Hauser Conducta GmbH + Co. KG",
    label: "Endress + Hauser Conducta GmbH + Co. KG",
  },
  { value: "Conergy AG", label: "Conergy AG" },
  { value: "Conseo GmbH", label: "Conseo GmbH" },
  { value: "Constantin Film AG", label: "Constantin Film AG" },
  { value: "Continental AG", label: "Continental AG" },
  {
    value: "Continental Teves AG & Co. oHG",
    label: "Continental Teves AG & Co. oHG",
  },
  {
    value: "Versicherungsverbund Die Continentale",
    label: "Versicherungsverbund Die Continentale",
  },
  { value: "CORA-IT GmbH", label: "CORA-IT GmbH" },
  {
    value: "Cornelsen Verlag GmbH & Co. oHG",
    label: "Cornelsen Verlag GmbH & Co. oHG",
  },
  { value: "Corporate Express", label: "Corporate Express" },
  { value: "Corporate Value Associates", label: "Corporate Value Associates" },
  {
    value: "Cosmopolitan Cosmetics GmbH",
    label: "Cosmopolitan Cosmetics GmbH",
  },
  { value: "CREATON AG", label: "CREATON AG" },
  { value: "CSC Ploenzke AG", label: "CSC Ploenzke AG" },
  {
    value: "Credit Suisse Deutschland AG",
    label: "Credit Suisse Deutschland AG",
  },
  { value: "CTcon GmbH", label: "CTcon GmbH" },
  { value: "Dachser GmbH & Co. KG", label: "Dachser GmbH & Co. KG" },
  { value: "DaimlerChrysler AG", label: "DaimlerChrysler AG" },
  { value: "Danone GmbH", label: "Danone GmbH" },
  { value: "data process GmbH", label: "data process GmbH" },
  {
    value: "dataform dialogservices GmbH",
    label: "dataform dialogservices GmbH",
  },
  { value: "DATEV eG", label: "DATEV eG" },
  {
    value: "dba Luftfahrtgesellschaft mbH",
    label: "dba Luftfahrtgesellschaft mbH",
  },
  {
    value: "DBV-Winterthur Versicherung Aktiengesellschaft",
    label: "DBV-Winterthur Versicherung Aktiengesellschaft",
  },
  {
    value: "DE-Consult Deutsche Eisenbahn-Consulting GmbH",
    label: "DE-Consult Deutsche Eisenbahn-Consulting GmbH",
  },
  { value: "Debeka-Hauptverwaltung", label: "Debeka-Hauptverwaltung" },
  { value: "debitel AG", label: "debitel AG" },
  {
    value: "DECATHLON Sportartikel GmbH & Co. KG",
    label: "DECATHLON Sportartikel GmbH & Co. KG",
  },
  { value: "Degussa AG", label: "Degussa AG" },
  {
    value: "Heinrich Deichmann-Schuhe GmbH & Co. KG",
    label: "Heinrich Deichmann-Schuhe GmbH & Co. KG",
  },
  {
    value: "DekaBank Deutsche Girozentrale",
    label: "DekaBank Deutsche Girozentrale",
  },
  { value: "DEKRA  Automobil GmbH", label: "DEKRA  Automobil GmbH" },
  { value: "DELL GmbH", label: "DELL GmbH" },
  { value: "Terex Corporation", label: "Terex Corporation" },
  {
    value: "DENSO AUTOMOTIVE Deutschland GmbH",
    label: "DENSO AUTOMOTIVE Deutschland GmbH",
  },
  { value: "DERTOUR GmbH & Co.KG", label: "DERTOUR GmbH & Co.KG" },
  { value: "Detecon International GmbH", label: "Detecon International GmbH" },
  {
    value: "Johann Dettendorfer Spedition Ferntrans GmbH & Co. KG",
    label: "Johann Dettendorfer Spedition Ferntrans GmbH & Co. KG",
  },
  {
    value: "Deutsche Anlagen-Leasing GmbH",
    label: "Deutsche Anlagen-Leasing GmbH",
  },
  { value: "Deutsche Bahn AG", label: "Deutsche Bahn AG" },
  { value: "Deutsche Bank AG", label: "Deutsche Bank AG" },
  { value: "Deutsche Bundesbank", label: "Deutsche Bundesbank" },
  {
    value: "Deutsche Flugsicherung GmbH",
    label: "Deutsche Flugsicherung GmbH",
  },
  {
    value: "Deutsche Genossenschafts-Hypothekenbank AG",
    label: "Deutsche Genossenschafts-Hypothekenbank AG",
  },
  { value: "Deutsche Kreditbank AG", label: "Deutsche Kreditbank AG" },
  { value: "Deutsche Steinkohle AG", label: "Deutsche Steinkohle AG" },
  {
    value: "Deutsche Structured Finance GmbH",
    label: "Deutsche Structured Finance GmbH",
  },
  {
    value: "Deutsche Zentral-Genossenschaftsbank",
    label: "Deutsche Zentral-Genossenschaftsbank",
  },
  { value: "Deutscher Fachverlag GmbH", label: "Deutscher Fachverlag GmbH" },
  {
    value: "DEUTSCHER HEROLD Allgemeine Versicherung AG",
    label: "DEUTSCHER HEROLD Allgemeine Versicherung AG",
  },
  { value: "Deutscher Ring", label: "Deutscher Ring" },
  {
    value: "Deutscher Sparkassen Verlag GmbH",
    label: "Deutscher Sparkassen Verlag GmbH",
  },
  {
    value: "Deutscher Taschenbuch Verlag GmbH & Co.KG",
    label: "Deutscher Taschenbuch Verlag GmbH & Co.KG",
  },
  {
    value: "Deutsches Elektronen-Synchrotron DESY",
    label: "Deutsches Elektronen-Synchrotron DESY",
  },
  {
    value:
      "deutsches nationaltheater & staatskapelle weimar Theaterbetriebs GmbH",
    label:
      "deutsches nationaltheater & staatskapelle weimar Theaterbetriebs GmbH",
  },
  { value: "Deutsches Theater", label: "Deutsches Theater" },
  {
    value:
      "DEVK Deutsche Eisenbahn Versicherung Sach- und HUK-Versicherungsverein a.G.",
    label:
      "DEVK Deutsche Eisenbahn Versicherung Sach- und HUK-Versicherungsverein a.G.",
  },
  {
    value: "DHL Express Vertriebs GmbH & Co. OHG",
    label: "DHL Express Vertriebs GmbH & Co. OHG",
  },
  { value: "Diageo Deutschland GmbH", label: "Diageo Deutschland GmbH" },
  {
    value: "Diamond Cluster International",
    label: "Diamond Cluster International",
  },
  {
    value: "Dichtungstechnik G. BRUSS GmbH & CO. KG",
    label: "Dichtungstechnik G. BRUSS GmbH & CO. KG",
  },
  {
    value: "Die Welt - Axel Springer AG",
    label: "Die Welt - Axel Springer AG",
  },
  { value: "Diehl Stiftung & Co. KG", label: "Diehl Stiftung & Co. KG" },
  {
    value: "Deutscher Industrie- und Handelskammertag (DIHK) e.V.",
    label: "Deutscher Industrie- und Handelskammertag (DIHK) e.V.",
  },
  {
    value: "DIS Deutscher Industrie Service AG",
    label: "DIS Deutscher Industrie Service AG",
  },
  {
    value: "DKV Deutsche Krankenversicherung AG",
    label: "DKV Deutsche Krankenversicherung AG",
  },
  {
    value: "dm-drogerie markt GmbH + Co. KG",
    label: "dm-drogerie markt GmbH + Co. KG",
  },
  { value: "DMR Consulting", label: "DMR Consulting" },
  { value: "DORMA GmbH + Co. KG", label: "DORMA GmbH + Co. KG" },
  {
    value: "Aloys F. Dornbracht GmbH & Co. KG",
    label: "Aloys F. Dornbracht GmbH & Co. KG",
  },
  { value: "DOUGLAS HOLDING AG", label: "DOUGLAS HOLDING AG" },
  {
    value: "Dow Deutschland GmbH & Co. OHG",
    label: "Dow Deutschland GmbH & Co. OHG",
  },
  {
    value: "Deutsche Post ITSolutions GmbH",
    label: "Deutsche Post ITSolutions GmbH",
  },
  {
    value: "Dr. Ebner, Dr. Stolz & Partner",
    label: "Dr. Ebner, Dr. Stolz & Partner",
  },
  {
    value: "Dr. Heimeier & Partner Management- und Personalberatung GmbH",
    label: "Dr. Heimeier & Partner Management- und Personalberatung GmbH",
  },
  {
    value: "Dr. August Oetker Nahrungsmittel KG",
    label: "Dr. August Oetker Nahrungsmittel KG",
  },
  {
    value: "Dr. Thomas + Partner GmbH & Co. KG",
    label: "Dr. Thomas + Partner GmbH & Co. KG",
  },
  { value: "Dresdner Bank AG", label: "Dresdner Bank AG" },
  { value: "Droege & Comp. GmbH", label: "Droege & Comp. GmbH" },
  { value: "DRONCO AG", label: "DRONCO AG" },
  { value: "Drueker & Co. GmbH", label: "Drueker & Co. GmbH" },
  { value: "DUNLOP GmbH & Co. KG", label: "DUNLOP GmbH & Co. KG" },
  { value: "Dyckerhoff AG", label: "Dyckerhoff AG" },
  {
    value: "Dynamit Nobel Kunststoff GmbH",
    label: "Dynamit Nobel Kunststoff GmbH",
  },
  { value: "E.ON edis AG", label: "E.ON edis AG" },
  { value: "EADS Deutschland GmbH", label: "EADS Deutschland GmbH" },
  { value: "eBay International AG", label: "eBay International AG" },
  { value: "ebc Consult GmbH", label: "ebc Consult GmbH" },
  {
    value: "ECE Projektmanagement G.m.b.H. & Co. KG",
    label: "ECE Projektmanagement G.m.b.H. & Co. KG",
  },
  { value: "Eckes AG", label: "Eckes AG" },
  { value: "ECKES & STOCK GmbH", label: "ECKES & STOCK GmbH" },
  {
    value: "Eckes-Granini GmbH & Co. KG",
    label: "Eckes-Granini GmbH & Co. KG",
  },
  { value: "Ecolab GmbH & Co. KG", label: "Ecolab GmbH & Co. KG" },
  {
    value: "EDAG Engineering + Design AG",
    label: "EDAG Engineering + Design AG",
  },
  { value: "EDS Deutschland GmbH", label: "EDS Deutschland GmbH" },
  { value: "Elastogran GmbH", label: "Elastogran GmbH" },
  { value: "Electronic Arts GmbH", label: "Electronic Arts GmbH" },
  { value: "ELMOS Semiconductor AG", label: "ELMOS Semiconductor AG" },
  { value: "ElringKlinger AG", label: "ElringKlinger AG" },
  {
    value: "EMI Music Germany GmbH & Co. KG",
    label: "EMI Music Germany GmbH & Co. KG",
  },
  { value: "ENERCON GmbH", label: "ENERCON GmbH" },
  {
    value: "ENSO Energie Sachsen Ost GmbH",
    label: "ENSO Energie Sachsen Ost GmbH",
  },
  {
    value: "Enterprise Rent-A-Car Company",
    label: "Enterprise Rent-A-Car Company",
  },
  { value: "E.ON AG", label: "E.ON AG" },
  { value: "E.ON Hanse AG", label: "E.ON Hanse AG" },
  { value: "EON Mitte AG", label: "EON Mitte AG" },
  {
    value: "E-Plus Service GmbH & Co.KG",
    label: "E-Plus Service GmbH & Co.KG",
  },
  { value: "EPSON Deutschland GmbH", label: "EPSON Deutschland GmbH" },
  {
    value: "ERGO Versicherungsgruppe AG",
    label: "ERGO Versicherungsgruppe AG",
  },
  { value: "Ericsson GmbH", label: "Ericsson GmbH" },
  { value: "ERIMA GmbH", label: "ERIMA GmbH" },
  {
    value: "Ernsting's family GmbH & Co. KG",
    label: "Ernsting's family GmbH & Co. KG",
  },
  {
    value: "esco - european salt company GmbH & Co. KG",
    label: "esco - european salt company GmbH & Co. KG",
  },
  { value: "Esprit Europe GmbH", label: "Esprit Europe GmbH" },
  { value: "Esselte Leitz GmbH & Co KG", label: "Esselte Leitz GmbH & Co KG" },
  { value: "ESSO Deutschland GmbH", label: "ESSO Deutschland GmbH" },
  { value: "Ethicon GmbH", label: "Ethicon GmbH" },
  { value: "euro engineering AG", label: "euro engineering AG" },
  {
    value: "European Space Agency ESA/ESOC",
    label: "European Space Agency ESA/ESOC",
  },
  {
    value: "EXCELSIS Business Technology AG",
    label: "EXCELSIS Business Technology AG",
  },
  { value: "extra", label: "extra" },
  { value: "ExxonMobil", label: "ExxonMobil" },
  {
    value: "Falk Marco Polo Interactive GmbH",
    label: "Falk Marco Polo Interactive GmbH",
  },
  { value: "FARO Technologies Inc.", label: "FARO Technologies Inc." },
  { value: "Faurecia", label: "Faurecia" },
  { value: "FeBa-Fensterbau GmbH", label: "FeBa-Fensterbau GmbH" },
  { value: "FEINFOCUS GmbH", label: "FEINFOCUS GmbH" },
  { value: "FERCHAU Engineering GmbH", label: "FERCHAU Engineering GmbH" },
  { value: "Ferrero oHG mbH", label: "Ferrero oHG mbH" },
  {
    value: "Ferromatik Milacron Maschinenbau GmbH",
    label: "Ferromatik Milacron Maschinenbau GmbH",
  },
  { value: "fertiva GmbH", label: "fertiva GmbH" },
  { value: "Festo AG & Co. KG", label: "Festo AG & Co. KG" },
  {
    value: "FiberMark Gessner GmbH & Co. KG",
    label: "FiberMark Gessner GmbH & Co. KG",
  },
  { value: "Fielmann AG", label: "Fielmann AG" },
  {
    value: "Bundesrepublik Deutschland Finanzagentur GmbH",
    label: "Bundesrepublik Deutschland Finanzagentur GmbH",
  },
  {
    value: "IndustriePlanung Fischer AG",
    label: "IndustriePlanung Fischer AG",
  },
  { value: "FJH AG", label: "FJH AG" },
  { value: "A. Friedr. Flender AG", label: "A. Friedr. Flender AG" },
  { value: "FLICK GOCKE SCHAUMBURG", label: "FLICK GOCKE SCHAUMBURG" },
  {
    value: "Flughafen Hannover-Langenhagen GmbH",
    label: "Flughafen Hannover-Langenhagen GmbH",
  },
  {
    value: "Fontin & Company Management Consulting GmbH",
    label: "Fontin & Company Management Consulting GmbH",
  },
  { value: "Ford-Werke AG", label: "Ford-Werke AG" },
  { value: "Ford Bank", label: "Ford Bank" },
  { value: "forum Verlag GmbH", label: "forum Verlag GmbH" },
  { value: "FRABA AG", label: "FRABA AG" },
  { value: "Framatome ANP GmbH", label: "Framatome ANP GmbH" },
  { value: "Framode GmbH", label: "Framode GmbH" },
  {
    value: "Verlagsgruppe Frankfurter Allgemeine Zeitung GmbH",
    label: "Verlagsgruppe Frankfurter Allgemeine Zeitung GmbH",
  },
  {
    value: "Frankfurter Versicherungs-AG",
    label: "Frankfurter Versicherungs-AG",
  },
  { value: "Fraport AG", label: "Fraport AG" },
  { value: "Fraunhofer Gesellschaft", label: "Fraunhofer Gesellschaft" },
  { value: "Fraunhofer-IMS", label: "Fraunhofer-IMS" },
  { value: "freenet.de AG", label: "freenet.de AG" },
  { value: "Fresenius SE", label: "Fresenius SE" },
  {
    value: "Freudenberg & Co. Kommanditgesellschaft",
    label: "Freudenberg & Co. Kommanditgesellschaft",
  },
  { value: "FTE automotive GmbH", label: "FTE automotive GmbH" },
  { value: "OTTO FUCHS KG", label: "OTTO FUCHS KG" },
  { value: "Fujisawa Deutschland GmbH", label: "Fujisawa Deutschland GmbH" },
  {
    value: "G& Personalservice GmbH & Co. KG",
    label: "G& Personalservice GmbH & Co. KG",
  },
  { value: "GARDENA AG", label: "GARDENA AG" },
  { value: "GEA Aktiengesellschaft", label: "GEA Aktiengesellschaft" },
  { value: "gedas deutschland GmbH", label: "gedas deutschland GmbH" },
  { value: "GE Europe GmbH", label: "GE Europe GmbH" },
  {
    value: "Genossenschaftsverband Frankfurt e.V.",
    label: "Genossenschaftsverband Frankfurt e.V.",
  },
  { value: "Georg Fischer AG", label: "Georg Fischer AG" },
  {
    value: "Gerling-Konzern Versicherungs-Beteiligungs-AG",
    label: "Gerling-Konzern Versicherungs-Beteiligungs-AG",
  },
  { value: "Germanwings GmbH", label: "Germanwings GmbH" },
  {
    value: "Gerolsteiner Brunnen GmbH & Co. KG",
    label: "Gerolsteiner Brunnen GmbH & Co. KG",
  },
  {
    value: "Gess & Partner GmbH Personalmanagement",
    label: "Gess & Partner GmbH Personalmanagement",
  },
  {
    value:
      "GETRAG Getriebe- und Zahnradfabrik Hermann Hagenmeyer GmbH & Cie KG",
    label:
      "GETRAG Getriebe- und Zahnradfabrik Hermann Hagenmeyer GmbH & Cie KG",
  },
  { value: "GEZ", label: "GEZ" },
  { value: "GEZE GmbH", label: "GEZE GmbH" },
  { value: "GfK", label: "GfK" },
  { value: "Giesecke & Devrient GmbH", label: "Giesecke & Devrient GmbH" },
  {
    value: "Gillette Gruppe Deutschland GmbH & Co. oHG",
    label: "Gillette Gruppe Deutschland GmbH & Co. oHG",
  },
  {
    value: "GKN Driveline Deutschland GmbH",
    label: "GKN Driveline Deutschland GmbH",
  },
  {
    value: "GlaxoSmithKline GmbH & Co. KG",
    label: "GlaxoSmithKline GmbH & Co. KG",
  },
  {
    value: "GLOBUS SB-Warenhaus Holding GmbH & Co. KG",
    label: "GLOBUS SB-Warenhaus Holding GmbH & Co. KG",
  },
  { value: "Glunz AG", label: "Glunz AG" },
  { value: "GOLDBECK GmbH", label: "GOLDBECK GmbH" },
  { value: "Goldman, Sachs & Co. oHG", label: "Goldman, Sachs & Co. oHG" },
  {
    value: "Goodrich Control Systems GmbH",
    label: "Goodrich Control Systems GmbH",
  },
  {
    value: "W.L. Gore & Associates GmbH",
    label: "W.L. Gore & Associates GmbH",
  },
  { value: "Gothaer Konzern", label: "Gothaer Konzern" },
  { value: "Gramm GmbH & Co. KG", label: "Gramm GmbH & Co. KG" },
  { value: "Greisel Klimanorm GmbH", label: "Greisel Klimanorm GmbH" },
  {
    value: "Grey Global Group Middle Europe",
    label: "Grey Global Group Middle Europe",
  },
  { value: "GROUP Technologies AG", label: "GROUP Technologies AG" },
  { value: "Gruner + Jahr AG & Co KG", label: "Gruner + Jahr AG & Co KG" },
  { value: "GWV Fachverlage GmbH", label: "GWV Fachverlage GmbH" },
  {
    value: "Hamburg-Mannheimer Versicherungs-AG",
    label: "Hamburg-Mannheimer Versicherungs-AG",
  },
  {
    value: "Verlagsgruppe Handelsblatt GmbH",
    label: "Verlagsgruppe Handelsblatt GmbH",
  },
  { value: "Franz Haniel & Cie. GmbH", label: "Franz Haniel & Cie. GmbH" },
  { value: "Hanno-Werk GmbH & Co KG", label: "Hanno-Werk GmbH & Co KG" },
  {
    value: "Hanse Klinikum Stralsund GmbH",
    label: "Hanse Klinikum Stralsund GmbH",
  },
  {
    value: "HanseMerkur Versicherungsgruppe",
    label: "HanseMerkur Versicherungsgruppe",
  },
  { value: "Hansgrohe AG", label: "Hansgrohe AG" },
  {
    value: "Harman/Becker Automotive Systems GmbH",
    label: "Harman/Becker Automotive Systems GmbH",
  },
  { value: "Harting KGaA", label: "Harting KGaA" },
  {
    value: "Rudolf Haufe Verlag GmbH & Co KG",
    label: "Rudolf Haufe Verlag GmbH & Co KG",
  },
  { value: "Hays AG", label: "Hays AG" },
  { value: "HDI Versicherung AG", label: "HDI Versicherung AG" },
  { value: "Hecht Contactlinsen GmbH", label: "Hecht Contactlinsen GmbH" },
  { value: "HeidelbergCement AG", label: "HeidelbergCement AG" },
  {
    value: "Heidelberger Druckmaschinen AG",
    label: "Heidelberger Druckmaschinen AG",
  },
  { value: "Heinrich Heine GmbH", label: "Heinrich Heine GmbH" },
  { value: "Heitk & Thumann KG", label: "Heitk & Thumann KG" },
  {
    value: "Helbling Management Consulting GmbH",
    label: "Helbling Management Consulting GmbH",
  },
  { value: "HELIOS Kliniken GmbH", label: "HELIOS Kliniken GmbH" },
  { value: "Hella KGaA Hueck & Co.", label: "Hella KGaA Hueck & Co." },
  {
    value: "Hellmann Worldwide Logistics GmbH & Co. KG",
    label: "Hellmann Worldwide Logistics GmbH & Co. KG",
  },
  { value: "HELM AG", label: "HELM AG" },
  { value: "Hengst GmbH & Co. KG", label: "Hengst GmbH & Co. KG" },
  { value: "Henkel KGaA", label: "Henkel KGaA" },
  { value: "Heraeus Holding GmbH", label: "Heraeus Holding GmbH" },
  {
    value: "HERFORT VAN KERKOM HOWER STREIT OHG",
    label: "HERFORT VAN KERKOM HOWER STREIT OHG",
  },
  { value: "Herlitz PBS AG", label: "Herlitz PBS AG" },
  {
    value: "Hermes Logistik GmbH & Co. KG",
    label: "Hermes Logistik GmbH & Co. KG",
  },
  { value: "Hewlett-Packard GmbH", label: "Hewlett-Packard GmbH" },
  { value: "Hilti Deutschland GmbH", label: "Hilti Deutschland GmbH" },
  { value: "Hilton International Group", label: "Hilton International Group" },
  {
    value: "HiPP GmbH & Co. Vertrieb KG",
    label: "HiPP GmbH & Co. Vertrieb KG",
  },
  { value: "Hitachi, Ltd.", label: "Hitachi, Ltd." },
  {
    value: "H & M Hennes & Mauritz GmbH",
    label: "H & M Hennes & Mauritz GmbH",
  },
  {
    value: "HOCHTIEF Aktiengesellschaft",
    label: "HOCHTIEF Aktiengesellschaft",
  },
  { value: "HOERBIGER Holding AG", label: "HOERBIGER Holding AG" },
  { value: "hohner Maschinenbau GmbH", label: "hohner Maschinenbau GmbH" },
  { value: "Holsten Brauerei AG", label: "Holsten Brauerei AG" },
  {
    value: "Honda Motor Europe (North) GmbH",
    label: "Honda Motor Europe (North) GmbH",
  },
  {
    value: "HORBACH Wirtschaftsberatung GmbH",
    label: "HORBACH Wirtschaftsberatung GmbH",
  },
  {
    value: "HPP  Harnischfeger, Pietsch & Partner",
    label: "HPP  Harnischfeger, Pietsch & Partner",
  },
  { value: "Hessischer Rundfunk", label: "Hessischer Rundfunk" },
  { value: "HSH Nordbank AG", label: "HSH Nordbank AG" },
  { value: "Rupp + Hubrach Optik GmbH", label: "Rupp + Hubrach Optik GmbH" },
  {
    value: "Buchhandlung Heinrich Hugendubel GmbH Co. KG",
    label: "Buchhandlung Heinrich Hugendubel GmbH Co. KG",
  },
  { value: "Humboldt Verlags GmbH", label: "Humboldt Verlags GmbH" },
  {
    value: "Hypothekenbank in Essen Aktiengesellschaft",
    label: "Hypothekenbank in Essen Aktiengesellschaft",
  },
  {
    value: "Bayerische Hypo- und Vereinsbank AG",
    label: "Bayerische Hypo- und Vereinsbank AG",
  },
  { value: "I-D Media AG", label: "I-D Media AG" },
  { value: "IAV GmbH", label: "IAV GmbH" },
  {
    value: "IBM Deutschland Entwicklung GmbH",
    label: "IBM Deutschland Entwicklung GmbH",
  },
  { value: "IBM Deutschland GmbH", label: "IBM Deutschland GmbH" },
  { value: "ICI plc", label: "ICI plc" },
  { value: "IDS Scheer AG", label: "IDS Scheer AG" },
  { value: "ifb AG", label: "ifb AG" },
  { value: "ifm electronic gmbh", label: "ifm electronic gmbh" },
  { value: "IG Metall Vorstand", label: "IG Metall Vorstand" },
  {
    value: "The Information Management Group IMG GmbH",
    label: "The Information Management Group IMG GmbH",
  },
  { value: "IIR Deutschland GmbH", label: "IIR Deutschland GmbH" },
  { value: "iiyama Deutschland GmbH", label: "iiyama Deutschland GmbH" },
  {
    value: "IKEA Deutschland GmbH & Co. KG",
    label: "IKEA Deutschland GmbH & Co. KG",
  },
  {
    value: "iks Informations Technologie GmbH",
    label: "iks Informations Technologie GmbH",
  },
  {
    value: "IKS Ingenieur Konstruktions Service GmbH",
    label: "IKS Ingenieur Konstruktions Service GmbH",
  },
  { value: "Immonet GmbH", label: "Immonet GmbH" },
  { value: "inamed GmbH", label: "inamed GmbH" },
  { value: "Infineon Technologies AG", label: "Infineon Technologies AG" },
  { value: "InfoTech AG", label: "InfoTech AG" },
  { value: "ING-DiBa AG", label: "ING-DiBa AG" },
  {
    value: "Ingram Micro Distribution GmbH",
    label: "Ingram Micro Distribution GmbH",
  },
  { value: "INNEO Solutions GmbH", label: "INNEO Solutions GmbH" },
  { value: "Intedis GmbH & Co. KG", label: "Intedis GmbH & Co. KG" },
  {
    value: "Integrated Dynamics Engineering GmbH",
    label: "Integrated Dynamics Engineering GmbH",
  },
  { value: "Intel", label: "Intel" },
  { value: "INTENSE AG", label: "INTENSE AG" },
  {
    value: "Intershop Communications AG",
    label: "Intershop Communications AG",
  },
  {
    value: "intra-Unternehmensberatung GmbH",
    label: "intra-Unternehmensberatung GmbH",
  },
  { value: "Inxmail GmbH", label: "Inxmail GmbH" },
  { value: "iPoint-systems gmbh", label: "iPoint-systems gmbh" },
  { value: "is Industrial Services AG", label: "is Industrial Services AG" },
  {
    value: "ISD INTERSEROH Dienstleistungs GmbH",
    label: "ISD INTERSEROH Dienstleistungs GmbH",
  },
  { value: "ISI Software GmbH", label: "ISI Software GmbH" },
  {
    value: "ITELLIUM Systems & Services",
    label: "ITELLIUM Systems & Services",
  },
  { value: "ITQ GmbH", label: "ITQ GmbH" },
  {
    value: "IVM Automotive Holding GmbH & Co. KG",
    label: "IVM Automotive Holding GmbH & Co. KG",
  },
  { value: "IWKA Aktiengesellschaft", label: "IWKA Aktiengesellschaft" },
  { value: "IXOS SOFTWARE AG", label: "IXOS SOFTWARE AG" },
  { value: "Janssen-Cilag GmbH", label: "Janssen-Cilag GmbH" },
  { value: "Jenapharm GmbH & Co. KG", label: "Jenapharm GmbH & Co. KG" },
  { value: "JENOPTIK AG", label: "JENOPTIK AG" },
  { value: "Deere & Company", label: "Deere & Company" },
  { value: "John Deere Vertrieb", label: "John Deere Vertrieb" },
  { value: "Johnson & Johnson GmbH", label: "Johnson & Johnson GmbH" },
  {
    value: "Johnson Controls GmbH Automotive Experience",
    label: "Johnson Controls GmbH Automotive Experience",
  },
  { value: "JOOP! GmbH", label: "JOOP! GmbH" },
  { value: "Jungheinrich AG", label: "Jungheinrich AG" },
  { value: "K+S Consulting GmbH", label: "K+S Consulting GmbH" },
  { value: "K+S Entsorgung GmbH", label: "K+S Entsorgung GmbH" },
  { value: "K+S KALI GmbH", label: "K+S KALI GmbH" },
  {
    value: "KAEFER Isoliertechnik GmbH & Co. KG",
    label: "KAEFER Isoliertechnik GmbH & Co. KG",
  },
  {
    value: "HANNING & KAHL GmbH & Co. KG",
    label: "HANNING & KAHL GmbH & Co. KG",
  },
  { value: "Kappa RapidCorr GmbH", label: "Kappa RapidCorr GmbH" },
  { value: "Wilhelm Karmann GmbH", label: "Wilhelm Karmann GmbH" },
  { value: "Karstadt Quelle AG", label: "Karstadt Quelle AG" },
  { value: "Karstadt Quelle Bank GmbH", label: "Karstadt Quelle Bank GmbH" },
  {
    value: "Karstadt Quelle Versicherungen",
    label: "Karstadt Quelle Versicherungen",
  },
  { value: "Karstadt Warenhaus AG", label: "Karstadt Warenhaus AG" },
  { value: "Kaufhof Warenhaus AG", label: "Kaufhof Warenhaus AG" },
  {
    value: "Kaufland Dienstleistung GmbH & Co. KG",
    label: "Kaufland Dienstleistung GmbH & Co. KG",
  },
  {
    value: "Kautex Textron GmbH & Co. KG",
    label: "Kautex Textron GmbH & Co. KG",
  },
  { value: "Keiper GmbH & Co. KG", label: "Keiper GmbH & Co. KG" },
  { value: "KELLOGG (DEUTSCHLAND) GMBH", label: "KELLOGG (DEUTSCHLAND) GMBH" },
  { value: "Kemper's Deutschland GmbH", label: "Kemper's Deutschland GmbH" },
  {
    value: "KEMPFER & KOLAKOVIC Personalmanagement GmbH",
    label: "KEMPFER & KOLAKOVIC Personalmanagement GmbH",
  },
  { value: "Kentucky Fried Chicken", label: "Kentucky Fried Chicken" },
  { value: "Kern GmbH", label: "Kern GmbH" },
  { value: "Kern Technik GmbH & Co. KG", label: "Kern Technik GmbH & Co. KG" },
  {
    value: "Kienbaum Consultants International GmbH",
    label: "Kienbaum Consultants International GmbH",
  },
  {
    value: "KiK Textilien und Non-Food GmbH",
    label: "KiK Textilien und Non-Food GmbH",
  },
  { value: "Kimmel Zahntechnik GmbH", label: "Kimmel Zahntechnik GmbH" },
  { value: "Klax gGmbH", label: "Klax gGmbH" },
  {
    value: "Ernst Klett Aktiengesellschaft",
    label: "Ernst Klett Aktiengesellschaft",
  },
  {
    value: "KMC Klausmeier Marketing Consultants GmbH",
    label: "KMC Klausmeier Marketing Consultants GmbH",
  },
  { value: "Knauf Gips KG", label: "Knauf Gips KG" },
  { value: "Knorr Bremse Gruppe", label: "Knorr Bremse Gruppe" },
  { value: "KOBRA Formen GmbH", label: "KOBRA Formen GmbH" },
  { value: "Kodak GmbH", label: "Kodak GmbH" },
  { value: "Koelnmesse GmbH", label: "Koelnmesse GmbH" },
  { value: "Koenig & Bauer AG", label: "Koenig & Bauer AG" },
  { value: "Konnex Logistik GmbH", label: "Konnex Logistik GmbH" },
  { value: "konzept: GmbH & Co. KG", label: "konzept: GmbH & Co. KG" },
  {
    value: "KPMG Deutsche Treuhand-Gesellschaft AG",
    label: "KPMG Deutsche Treuhand-Gesellschaft AG",
  },
  {
    value: "Kraft Foods Deutschland GmbH",
    label: "Kraft Foods Deutschland GmbH",
  },
  {
    value: "Krauss-Maffei Wegmann GmbH & Co KG",
    label: "Krauss-Maffei Wegmann GmbH & Co KG",
  },
  { value: "Krombacher Brauerei", label: "Krombacher Brauerei" },
  { value: "Krones AG", label: "Krones AG" },
  { value: "KUKA Roboter GmbH", label: "KUKA Roboter GmbH" },
  { value: "KUKA Schweissanlagen GmbH", label: "KUKA Schweissanlagen GmbH" },
  { value: "K+S Aktiengesellschaft", label: "K+S Aktiengesellschaft" },
  {
    value: "HUDSON KUNERT Vertriebs GmbH",
    label: "HUDSON KUNERT Vertriebs GmbH",
  },
  { value: "KWS SAAT AG", label: "KWS SAAT AG" },
  {
    value: "KYOCERA MITA DEUTSCHLAND GmbH",
    label: "KYOCERA MITA DEUTSCHLAND GmbH",
  },
  {
    value: "LBS Bayerische Landesbausparkasse",
    label: "LBS Bayerische Landesbausparkasse",
  },
  {
    value: "LBS Norddeutsche Landesbausparkasse Berlin - Hannover",
    label: "LBS Norddeutsche Landesbausparkasse Berlin - Hannover",
  },
  { value: "LEGO GmbH", label: "LEGO GmbH" },
  { value: "Lehman Brothers", label: "Lehman Brothers" },
  { value: "Lehmann & Voss & Co. KG", label: "Lehmann & Voss & Co. KG" },
  { value: "Lenze AG", label: "Lenze AG" },
  { value: "LEONI AG", label: "LEONI AG" },
  {
    value: "LG Electronics Deutschland GmbH",
    label: "LG Electronics Deutschland GmbH",
  },
  {
    value: "Lidl Dienstleistung GmbH & Co. KG",
    label: "Lidl Dienstleistung GmbH & Co. KG",
  },
  {
    value: "Liebherr-International Deutschland GmbH",
    label: "Liebherr-International Deutschland GmbH",
  },
  { value: "LifeScan", label: "LifeScan" },
  {
    value: "Lifta Lift und Antrieb GmbH",
    label: "Lifta Lift und Antrieb GmbH",
  },
  { value: "Lilly Pharma Holding GmbH", label: "Lilly Pharma Holding GmbH" },
  { value: "Linde AG", label: "Linde AG" },
  { value: "LogicaCMG", label: "LogicaCMG" },
  {
    value: "LRP Landesbank Rheinland-Pfalz",
    label: "LRP Landesbank Rheinland-Pfalz",
  },
  {
    value: "LSK Kunststoffverarbeitung GmbH",
    label: "LSK Kunststoffverarbeitung GmbH",
  },
  {
    value: "LTU Lufttransport-Unternehmen GmbH",
    label: "LTU Lufttransport-Unternehmen GmbH",
  },
  {
    value: "Lucent TechnologiesNetwork Systems GmbH",
    label: "Lucent TechnologiesNetwork Systems GmbH",
  },
  { value: "Deutsche Lufthansa AG", label: "Deutsche Lufthansa AG" },
  { value: "Lufthansa Technik AG", label: "Lufthansa Technik AG" },
  { value: "Lycos Europe GmbH", label: "Lycos Europe GmbH" },
  { value: "Mack Rides GmbH & Co. KG", label: "Mack Rides GmbH & Co. KG" },
  { value: "Magirus AG", label: "Magirus AG" },
  { value: "MAHLE GmbH", label: "MAHLE GmbH" },
  {
    value: "Mahr Metrology - Deutschland",
    label: "Mahr Metrology - Deutschland",
  },
  { value: "MAN AG", label: "MAN AG" },
  { value: "MANN+HUMMEL GMBH", label: "MANN+HUMMEL GMBH" },
  { value: "MANPOWER GmbH & Co. KG", label: "MANPOWER GmbH & Co. KG" },
  { value: "Masterfoods GmbH", label: "Masterfoods GmbH" },
  { value: "Materna GmbH", label: "Materna GmbH" },
  {
    value: "mechaprint MAUTHE Kalender Verlag GmbH",
    label: "mechaprint MAUTHE Kalender Verlag GmbH",
  },
  {
    value: "Mazda Motors (Deutschland) GmbH",
    label: "Mazda Motors (Deutschland) GmbH",
  },
  {
    value: "McDonald's Deutschland Inc.",
    label: "McDonald's Deutschland Inc.",
  },
  { value: "McKinsey & Company, Inc.", label: "McKinsey & Company, Inc." },
  { value: "McNeil GmbH & Co. oHG", label: "McNeil GmbH & Co. oHG" },
  { value: "Mitteldeutscher Rundfunk", label: "Mitteldeutscher Rundfunk" },
  {
    value: "Media Saturn Systemzentrale GmbH",
    label: "Media Saturn Systemzentrale GmbH",
  },
  { value: "Medtronic GmbH", label: "Medtronic GmbH" },
  { value: "Meier's Weltreisen", label: "Meier's Weltreisen" },
  { value: "Meinke GmbH", label: "Meinke GmbH" },
  {
    value: "Melitta Beratungs- und Verwaltungs GmbH & Co. KG",
    label: "Melitta Beratungs- und Verwaltungs GmbH & Co. KG",
  },
  {
    value: "Mercer Management Consulting",
    label: "Mercer Management Consulting",
  },
  { value: "Merck KGaA", label: "Merck KGaA" },
  { value: "Merckle GmbH", label: "Merckle GmbH" },
  {
    value: "Merrill Lynch Management GmbH",
    label: "Merrill Lynch Management GmbH",
  },
  { value: "Metabowerke GmbH", label: "Metabowerke GmbH" },
  { value: "method park Software AG", label: "method park Software AG" },
  {
    value: "METRO Cash & Carry Deutschland GmbH",
    label: "METRO Cash & Carry Deutschland GmbH",
  },
  { value: "METRO AG", label: "METRO AG" },
  { value: "Metso Lindemann GmbH", label: "Metso Lindemann GmbH" },
  {
    value: "Michael Page International (Deutschland) GmbH",
    label: "Michael Page International (Deutschland) GmbH",
  },
  {
    value: "Michelin Reifenwerke AG & Co KGaA",
    label: "Michelin Reifenwerke AG & Co KGaA",
  },
  { value: "Miele & Cie. KG", label: "Miele & Cie. KG" },
  { value: "Miller Energiesparsysteme", label: "Miller Energiesparsysteme" },
  { value: "Microsoft Deutschland GmbH", label: "Microsoft Deutschland GmbH" },
  {
    value: "Mitsubishi Electric Europe B.V",
    label: "Mitsubishi Electric Europe B.V",
  },
  {
    value: "Mitsubishi HiTec Paper Flensburg GmbH",
    label: "Mitsubishi HiTec Paper Flensburg GmbH",
  },
  { value: "MLP AG", label: "MLP AG" },
  { value: "Molda AG", label: "Molda AG" },
  { value: "Monitor Group", label: "Monitor Group" },
  { value: "Morgan Stanley Bank AG", label: "Morgan Stanley Bank AG" },
  { value: "MorphoSys AG", label: "MorphoSys AG" },
  { value: "Motorola GmbH", label: "Motorola GmbH" },
  { value: "MSD SHARP & DOHME GMBH", label: "MSD SHARP & DOHME GMBH" },
  { value: "msg systems ag", label: "msg systems ag" },
  { value: "MTU Aero Engines GmbH", label: "MTU Aero Engines GmbH" },
  { value: "MTV Networks GmbH & Co OHG", label: "MTV Networks GmbH & Co OHG" },
  { value: "Mundwerk AG", label: "Mundwerk AG" },
  { value: "Muster GmbH", label: "Muster GmbH" },
  { value: "Nassauische Sparkasse", label: "Nassauische Sparkasse" },
  { value: "Navigon AG", label: "Navigon AG" },
  { value: "ND SatCom AG", label: "ND SatCom AG" },
  { value: "Norddeutscher Rundfunk", label: "Norddeutscher Rundfunk" },
  { value: "Neckermann Versand AG", label: "Neckermann Versand AG" },
  {
    value: "New Yorker S.H.K. Jeans GmbH",
    label: "New Yorker S.H.K. Jeans GmbH",
  },
  { value: "Nintendo of Europe GmbH", label: "Nintendo of Europe GmbH" },
  { value: "Nokia GmbH", label: "Nokia GmbH" },
  {
    value: "NORD/LB Norddeutsche Landesbank",
    label: "NORD/LB Norddeutsche Landesbank",
  },
  { value: "Nordzucker AG", label: "Nordzucker AG" },
  { value: "norisbank AG", label: "norisbank AG" },
  {
    value: "NORMA Lebensmittelfilialbetrieb GmbH & Co.KG",
    label: "NORMA Lebensmittelfilialbetrieb GmbH & Co.KG",
  },
  {
    value: "NORMA Lebensmittelfilialbetrieb GmbH & Co.KG",
    label: "NORMA Lebensmittelfilialbetrieb GmbH & Co.KG",
  },
  {
    value: "Nortel Networks Germany GmbH & Co.KG",
    label: "Nortel Networks Germany GmbH & Co.KG",
  },
  { value: "Novartis International AG", label: "Novartis International AG" },
  { value: "Novelis Deutschland GmbH", label: "Novelis Deutschland GmbH" },
  { value: "Novell Deutschland GmbH", label: "Novell Deutschland GmbH" },
  { value: "Novo Nordisk Pharma GmbH", label: "Novo Nordisk Pharma GmbH" },
  {
    value: "NOWEDA eG Apothekergenossenschaft",
    label: "NOWEDA eG Apothekergenossenschaft",
  },
  {
    value: "O2 (Germany) GmbH & Co. OHG",
    label: "O2 (Germany) GmbH & Co. OHG",
  },
  { value: "OBI Franchise Center", label: "OBI Franchise Center" },
  { value: "OMICRON electronics GmbH", label: "OMICRON electronics GmbH" },
  { value: "Adam Opel AG", label: "Adam Opel AG" },
  {
    value: "Open Systems Consulting GmbH",
    label: "Open Systems Consulting GmbH",
  },
  { value: "OPITZ CONSULTING GmbH", label: "OPITZ CONSULTING GmbH" },
  { value: "Optimus Logistics GmbH", label: "Optimus Logistics GmbH" },
  { value: "Oracle", label: "Oracle" },
  { value: "ORGA GmbH", label: "ORGA GmbH" },
  { value: "Orsay GmbH", label: "Orsay GmbH" },
  { value: "ORTHO BIOTECH", label: "ORTHO BIOTECH" },
  {
    value: "Oliver Schrott Kommunikations GmbH",
    label: "Oliver Schrott Kommunikations GmbH",
  },
  { value: "Osram GmbH", label: "Osram GmbH" },
  { value: "Otis GmbH & Co. OHG", label: "Otis GmbH & Co. OHG" },
  { value: "Otto (GmbH & Co KG)", label: "Otto (GmbH & Co KG)" },
  {
    value: "Otto Henning & Company Strategy Consultants GmbH",
    label: "Otto Henning & Company Strategy Consultants GmbH",
  },
  { value: "PA Consulting Group GmbH", label: "PA Consulting Group GmbH" },
  { value: "Panasonic Deutschland GmbH", label: "Panasonic Deutschland GmbH" },
  { value: "PASS IT-Consulting", label: "PASS IT-Consulting" },
  { value: "PDR Recycling GmbH + Co KG", label: "PDR Recycling GmbH + Co KG" },
  {
    value: "Pelikan Vertriebsgesellschaft mbH & Co. KG",
    label: "Pelikan Vertriebsgesellschaft mbH & Co. KG",
  },
  { value: "Pepperl+Fuchs GmbH", label: "Pepperl+Fuchs GmbH" },
  { value: "Peter Hahn GmbH", label: "Peter Hahn GmbH" },
  { value: "PEUGEOT Deutschland GmbH", label: "PEUGEOT Deutschland GmbH" },
  { value: "Pfizer GmbH", label: "Pfizer GmbH" },
  {
    value: "Dr. R. Pfleger Chemische Fabrik GmbH",
    label: "Dr. R. Pfleger Chemische Fabrik GmbH",
  },
  { value: "Pharma Rent GmbH", label: "Pharma Rent GmbH" },
  { value: "Pharma Resources GmbH", label: "Pharma Resources GmbH" },
  { value: "Philip Morris GmbH", label: "Philip Morris GmbH" },
  { value: "Philips GmbH", label: "Philips GmbH" },
  {
    value: "Phoenix Contact GmbH & Co. KG",
    label: "Phoenix Contact GmbH & Co. KG",
  },
  {
    value: "PHOENIX Pharmahandel Aktiengesellschaft & Co KG",
    label: "PHOENIX Pharmahandel Aktiengesellschaft & Co KG",
  },
  { value: "Phonak GmbH", label: "Phonak GmbH" },
  { value: "Pixelpark AG", label: "Pixelpark AG" },
  { value: "PLANAT GmbH", label: "PLANAT GmbH" },
  {
    value: "Plansecur Management GmbH & Co. Marketing und Service KG",
    label: "Plansecur Management GmbH & Co. Marketing und Service KG",
  },
  {
    value: "Plus Warenhandelsgesellschaft mbH",
    label: "Plus Warenhandelsgesellschaft mbH",
  },
  { value: "PM-International AG", label: "PM-International AG" },
  { value: "Polysius AG", label: "Polysius AG" },
  {
    value: "POLYTEC AUTOMOTIVE GmbH & Co. KG",
    label: "POLYTEC AUTOMOTIVE GmbH & Co. KG",
  },
  {
    value: "Dr. Ing. h.c. F. Porsche AG",
    label: "Dr. Ing. h.c. F. Porsche AG",
  },
  { value: "L. Possehl & Co. mbH", label: "L. Possehl & Co. mbH" },
  { value: "Deutsche Post AG", label: "Deutsche Post AG" },
  { value: "Deutsche Postbank AG", label: "Deutsche Postbank AG" },
  { value: "PosterNetwork AG", label: "PosterNetwork AG" },
  { value: "PPI Financial Systems GmbH", label: "PPI Financial Systems GmbH" },
  { value: "PR & More", label: "PR & More" },
  {
    value: "Prettl GmbH Magnet- und Schaltertechnik",
    label: "Prettl GmbH Magnet- und Schaltertechnik",
  },
  { value: "PricewaterhouseCoopers", label: "PricewaterhouseCoopers" },
  {
    value: "pro-Unicus Financial Consulting AG",
    label: "pro-Unicus Financial Consulting AG",
  },
  { value: "proALPHA Software AG", label: "proALPHA Software AG" },
  {
    value: "Procter & Gamble Service GmbH",
    label: "Procter & Gamble Service GmbH",
  },
  { value: "Profectis GmbH", label: "Profectis GmbH" },
  {
    value: "PROFI Engineering Systems AG",
    label: "PROFI Engineering Systems AG",
  },
  { value: "Promerit AG", label: "Promerit AG" },
  { value: "ProSiebenSat.1 Media AG", label: "ProSiebenSat.1 Media AG" },
  { value: "PROSTEP AG", label: "PROSTEP AG" },
  { value: "psychonomics GmbH", label: "psychonomics GmbH" },
  { value: "PTV AG", label: "PTV AG" },
  { value: "PUMA AG", label: "PUMA AG" },
  { value: "QGROUP ERBEE ASSOCCIATES", label: "QGROUP ERBEE ASSOCCIATES" },
  { value: "Quelle AG", label: "Quelle AG" },
  {
    value: "Querschiesser Unternehmensberatung GmbH & Co. KG",
    label: "Querschiesser Unternehmensberatung GmbH & Co. KG",
  },
  { value: "Q_PERIOR AG", label: "Q_PERIOR AG" },
  { value: "Radio Bremen", label: "Radio Bremen" },
  { value: "RAG Aktiengesellschaft", label: "RAG Aktiengesellschaft" },
  {
    value: "RAM Engineering und Anlagenbau GmbH",
    label: "RAM Engineering und Anlagenbau GmbH",
  },
  {
    value: "Randstad Deutschland GmbH & Co. KG",
    label: "Randstad Deutschland GmbH & Co. KG",
  },
  { value: "Rasmussen GmbH", label: "Rasmussen GmbH" },
  { value: "ratiopharm GmbH", label: "ratiopharm GmbH" },
  {
    value: "Rundfunk Berlin-Brandenburg",
    label: "Rundfunk Berlin-Brandenburg",
  },
  { value: "real,- SB Warenhaus GmbH", label: "real,- SB Warenhaus GmbH" },
  { value: "RECARO GmbH & Co. KG,", label: "RECARO GmbH & Co. KG," },
  {
    value: "ICRC International Committee of the Red Cross",
    label: "ICRC International Committee of the Red Cross",
  },
  { value: "REHAU AG+Co", label: "REHAU AG+Co" },
  { value: "REINZ-Dichtungs-GmbH", label: "REINZ-Dichtungs-GmbH" },
  { value: "RENA Sondermaschinen GmbH", label: "RENA Sondermaschinen GmbH" },
  {
    value: "Renesas Semiconductor Europe (Landshut) GmbH",
    label: "Renesas Semiconductor Europe (Landshut) GmbH",
  },
  {
    value: "Renesas Technology Europe GmbH",
    label: "Renesas Technology Europe GmbH",
  },
  { value: "RENK Aktiengesellschaft", label: "RENK Aktiengesellschaft" },
  { value: "REpower Systems AG", label: "REpower Systems AG" },
  { value: "Repower Systems AG", label: "Repower Systems AG" },
  {
    value: "Reuschel & Co. Kommanditgesellschaft",
    label: "Reuschel & Co. Kommanditgesellschaft",
  },
  {
    value: "REWE-Zentral-Aktiengesellschaft",
    label: "REWE-Zentral-Aktiengesellschaft",
  },
  { value: "Rheinhold & Mahla AG", label: "Rheinhold & Mahla AG" },
  { value: "Rheinmetall AG", label: "Rheinmetall AG" },
  { value: "ritterwerk GmbH", label: "ritterwerk GmbH" },
  {
    value: "Robert Half Deutschland GmbH & Co. KG",
    label: "Robert Half Deutschland GmbH & Co. KG",
  },
  { value: "F. Hoffmann-La Roche AG", label: "F. Hoffmann-La Roche AG" },
  { value: "Roche Diagnostics GmbH", label: "Roche Diagnostics GmbH" },
  {
    value: "ROHDE & SCHWARZ GmbH & Co. KG",
    label: "ROHDE & SCHWARZ GmbH & Co. KG",
  },
  { value: "Roka Werk GmbH", label: "Roka Werk GmbH" },
  {
    value: "Roland Berger Strategy Consultants",
    label: "Roland Berger Strategy Consultants",
  },
  {
    value: "Rolls-Royce Deutschland Ltd. & Co. KG",
    label: "Rolls-Royce Deutschland Ltd. & Co. KG",
  },
  { value: "Dirk Rossmann GmbH", label: "Dirk Rossmann GmbH" },
  { value: "RTL Television GmbH", label: "RTL Television GmbH" },
  {
    value: "RUNNERS POINT Warenhandelsgesellschaft mbH",
    label: "RUNNERS POINT Warenhandelsgesellschaft mbH",
  },
  { value: "R+V Versicherung AG", label: "R+V Versicherung AG" },
  { value: "RWE AG", label: "RWE AG" },
  { value: "Sachsen LB", label: "Sachsen LB" },
  {
    value: "Sal. Oppenheim jr. & Cie. KGaA",
    label: "Sal. Oppenheim jr. & Cie. KGaA",
  },
  {
    value: "Salzgitter Aktiengesellschaft",
    label: "Salzgitter Aktiengesellschaft",
  },
  {
    value: "Sana Kliniken GmbH & Co. KGaA",
    label: "Sana Kliniken GmbH & Co. KGaA",
  },
  { value: "Sanacorp Pharmahandel AG", label: "Sanacorp Pharmahandel AG" },
  {
    value: "Sanofi-Aventis Deutschland GmbH",
    label: "Sanofi-Aventis Deutschland GmbH",
  },
  { value: "SAP AG", label: "SAP AG" },
  { value: "Sartorius AG", label: "Sartorius AG" },
  { value: "SAS Deutschland", label: "SAS Deutschland" },
  {
    value: "SBK, Siemens- Betriebskrankenkasse",
    label: "SBK, Siemens- Betriebskrankenkasse",
  },
  { value: "SCA HYGIENE PRODUCTS", label: "SCA HYGIENE PRODUCTS" },
  { value: "Schaeffler KG", label: "Schaeffler KG" },
  { value: "Carl Schenck AG", label: "Carl Schenck AG" },
  { value: "Schenck Process GmbH", label: "Schenck Process GmbH" },
  { value: "Schenker AG", label: "Schenker AG" },
  { value: "Schering AG", label: "Schering AG" },
  { value: "Fa. ANTON SCHLECKER", label: "Fa. ANTON SCHLECKER" },
  {
    value: "SCHLEIFRING und APPARATEBAU GmbH",
    label: "SCHLEIFRING und APPARATEBAU GmbH",
  },
  { value: "Schmitt GmbH", label: "Schmitt GmbH" },
  {
    value: "Schmitz-Werke GmbH + Co. KG",
    label: "Schmitz-Werke GmbH + Co. KG",
  },
  {
    value: "Schneider Betonwerk GmbH + Co. KG",
    label: "Schneider Betonwerk GmbH + Co. KG",
  },
  { value: "Schnellecke", label: "Schnellecke" },
  { value: "Schott AG", label: "Schott AG" },
  {
    value: "Schreiner Group GmbH & Co. KG",
    label: "Schreiner Group GmbH & Co. KG",
  },
  { value: "Schuberth Engineering AG", label: "Schuberth Engineering AG" },
  { value: "Schwab Versand GmbH", label: "Schwab Versand GmbH" },
  { value: "science + computing ag", label: "science + computing ag" },
  {
    value: "sd& AG, software design & management",
    label: "sd& AG, software design & management",
  },
  { value: "Seidenschwarz & Comp. GmbH", label: "Seidenschwarz & Comp. GmbH" },
  {
    value: "Sennheiser electronic GmbH & Co. KG",
    label: "Sennheiser electronic GmbH & Co. KG",
  },
  { value: "SERVIER Deutschland GmbH", label: "SERVIER Deutschland GmbH" },
  {
    value: "Setron GmbH service distribution",
    label: "Setron GmbH service distribution",
  },
  { value: "Sevenval GmbH", label: "Sevenval GmbH" },
  { value: "SEW-EURODRIVE GmbH & Co KG", label: "SEW-EURODRIVE GmbH & Co KG" },
  { value: "Shell in Deutschland", label: "Shell in Deutschland" },
  { value: "SICK AG", label: "SICK AG" },
  { value: "Siemens VDO Automotive AG", label: "Siemens VDO Automotive AG" },
  {
    value: "Siemens Financial Services GmbH",
    label: "Siemens Financial Services GmbH",
  },
  {
    value: "Siemens Management Consulting",
    label: "Siemens Management Consulting",
  },
  { value: "Siemens VDO Automotive AG", label: "Siemens VDO Automotive AG" },
  {
    value: "SIG Combibloc International AG",
    label: "SIG Combibloc International AG",
  },
  {
    value: "SIGNAL IDUNA Gruppe Versicherungen und Finanzen",
    label: "SIGNAL IDUNA Gruppe Versicherungen und Finanzen",
  },
  { value: "Silicon Graphics GmbH", label: "Silicon Graphics GmbH" },
  {
    value: "SIM Communication Center GmbH",
    label: "SIM Communication Center GmbH",
  },
  { value: "SimCorp GmbH", label: "SimCorp GmbH" },
  { value: "Sixt Aktiengesellschaft", label: "Sixt Aktiengesellschaft" },
  { value: "SKF GmbH", label: "SKF GmbH" },
  { value: "SMA Solar Technology AG", label: "SMA Solar Technology AG" },
  { value: "smart gmbh", label: "smart gmbh" },
  { value: "SMC Pneumatik GmbH", label: "SMC Pneumatik GmbH" },
  { value: "SMS Demag AG", label: "SMS Demag AG" },
  { value: "Software AG", label: "Software AG" },
  {
    value: "Solon Management Consulting GmbH & Co. KG",
    label: "Solon Management Consulting GmbH & Co. KG",
  },
  { value: "SOLVAY GmbH", label: "SOLVAY GmbH" },
  {
    value: "SOMATEX Medical Technologies GmbH",
    label: "SOMATEX Medical Technologies GmbH",
  },
  { value: "Sony Deutschland GmbH", label: "Sony Deutschland GmbH" },
  {
    value: "Sparkassen-Finanzportal GmbH",
    label: "Sparkassen-Finanzportal GmbH",
  },
  {
    value: "SPIEGEL-Verlag Rudolf Augstein GmbH & Co. KG",
    label: "SPIEGEL-Verlag Rudolf Augstein GmbH & Co. KG",
  },
  {
    value: "Springer Science+Business Media",
    label: "Springer Science+Business Media",
  },
  {
    value: "Springer & Jacoby Werbung GmbH & Co. KG",
    label: "Springer & Jacoby Werbung GmbH & Co. KG",
  },
  {
    value: "SQS Software Quality Systems AG",
    label: "SQS Software Quality Systems AG",
  },
  {
    value: "Staatsoper Unter den Linden",
    label: "Staatsoper Unter den Linden",
  },
  { value: "Standard Life Versicherung", label: "Standard Life Versicherung" },
  { value: "start2grow", label: "start2grow" },
  { value: "Statistisches Bundesamt", label: "Statistisches Bundesamt" },
  { value: "STEAG Aktiengesellschaft", label: "STEAG Aktiengesellschaft" },
  { value: "Stellenboersen.de", label: "Stellenboersen.de" },
  {
    value: "Steria Mummert Consulting AG",
    label: "Steria Mummert Consulting AG",
  },
  { value: "Stern Stewart & Co.", label: "Stern Stewart & Co." },
  { value: "ANDREAS STIHL AG & Co. KG", label: "ANDREAS STIHL AG & Co. KG" },
  { value: "AUGUST STORCK KG", label: "AUGUST STORCK KG" },
  { value: "Strathmann AG & Co.", label: "Strathmann AG & Co." },
  { value: "STRATO Medien AG", label: "STRATO Medien AG" },
  { value: "Streiff & Helmold GmbH", label: "Streiff & Helmold GmbH" },
  { value: "SULO Gruppe", label: "SULO Gruppe" },
  { value: "Sun Microsystems GmbH", label: "Sun Microsystems GmbH" },
  { value: "SUSAT & PARTNER OHG", label: "SUSAT & PARTNER OHG" },
  { value: "SWF Krantechnik GmbH", label: "SWF Krantechnik GmbH" },
  { value: "Symrise GmbH & Co. KG", label: "Symrise GmbH & Co. KG" },
  {
    value: "T-Systems Multimedia Solutions GmbH",
    label: "T-Systems Multimedia Solutions GmbH",
  },
  { value: "TARGOBANK AG & Co. KGaA", label: "TARGOBANK AG & Co. KGaA" },
  { value: "Tchibo GmbH", label: "Tchibo GmbH" },
  { value: "Techniker Krankenkasse", label: "Techniker Krankenkasse" },
  { value: "TECON Technologies AG", label: "TECON Technologies AG" },
  { value: "Deutsche Telekom AG", label: "Deutsche Telekom AG" },
  { value: "Teles AG", label: "Teles AG" },
  {
    value: "Tengelmann Warenhandelsgesellschaft KG",
    label: "Tengelmann Warenhandelsgesellschaft KG",
  },
  { value: "Tenovis GmbH & Co. KG", label: "Tenovis GmbH & Co. KG" },
  { value: "tesa AG", label: "tesa AG" },
  {
    value: "Texas Instruments Deutschland GmbH",
    label: "Texas Instruments Deutschland GmbH",
  },
  { value: "THALIS AG", label: "THALIS AG" },
  { value: "Thomas Cook AG", label: "Thomas Cook AG" },
  { value: "ThyssenKrupp AG", label: "ThyssenKrupp AG" },
  {
    value: "TietoEnator Deutschland GmbH",
    label: "TietoEnator Deutschland GmbH",
  },
  { value: "Timken Germany GmbH", label: "Timken Germany GmbH" },
  {
    value: "TNT Holdings (Deutschland) GmbH",
    label: "TNT Holdings (Deutschland) GmbH",
  },
  { value: "Toll Collect GmbH", label: "Toll Collect GmbH" },
  { value: "T-Online International AG", label: "T-Online International AG" },
  {
    value: "Torex Retail Solutions GmbH",
    label: "Torex Retail Solutions GmbH",
  },
  { value: "TOTAL Deutschland GmbH", label: "TOTAL Deutschland GmbH" },
  { value: "Toyota Deutschland GmbH", label: "Toyota Deutschland GmbH" },
  { value: "TOYS", label: "TOYS" },
  { value: "TRACTO-TECHNIK GmbH", label: "TRACTO-TECHNIK GmbH" },
  { value: "Transcoject GmbH & Co. KG", label: "Transcoject GmbH & Co. KG" },
  {
    value: "TransferZentrum Mikroelektronik (TZM)",
    label: "TransferZentrum Mikroelektronik (TZM)",
  },
  { value: "Trumpf GmbH + Co. KG", label: "Trumpf GmbH + Co. KG" },
  {
    value: "TRW Automotive Body Control Systems GmbH",
    label: "TRW Automotive Body Control Systems GmbH",
  },
  { value: "TUI AG", label: "TUI AG" },
  { value: "UBS", label: "UBS" },
  {
    value: "UBT See- und Hafenspedition GmbH",
    label: "UBT See- und Hafenspedition GmbH",
  },
  {
    value: "Uhlmann Pac-Systeme GmbH & Co. KG",
    label: "Uhlmann Pac-Systeme GmbH & Co. KG",
  },
  { value: "Ullstein Verlag", label: "Ullstein Verlag" },
  { value: "Semper idem Underberg AG", label: "Semper idem Underberg AG" },
  { value: "Unilever  Deutschland GmbH", label: "Unilever  Deutschland GmbH" },
  { value: "Union Investment ", label: "Union Investment " },
  { value: "universa Versicherungen", label: "universa Versicherungen" },
  { value: "UPM", label: "UPM" },
  {
    value: "United Parcel Service Deutschland Inc. & Co. OHG",
    label: "United Parcel Service Deutschland Inc. & Co. OHG",
  },
  { value: "Vaillant GmbH", label: "Vaillant GmbH" },
  { value: "Valeo GmbH", label: "Valeo GmbH" },
  {
    value: "Vallourec & Mannesmann Tubes AG",
    label: "Vallourec & Mannesmann Tubes AG",
  },
  { value: "Varta Consumer Batteries", label: "Varta Consumer Batteries" },
  { value: "VARTA Microbattery GmbH", label: "VARTA Microbattery GmbH" },
  { value: "Vattenfall Europe AG", label: "Vattenfall Europe AG" },
  {
    value: "VDI Verein Deutscher Ingenieure e.V.",
    label: "VDI Verein Deutscher Ingenieure e.V.",
  },
  { value: "VDI Verlag GmbH", label: "VDI Verlag GmbH" },
  { value: "Vemag Maschinenbau GmbH", label: "Vemag Maschinenbau GmbH" },
  {
    value: "Verband der privaten Krankenversicherung e.V.",
    label: "Verband der privaten Krankenversicherung e.V.",
  },
  { value: "Vereins- und Westbank AG", label: "Vereins- und Westbank AG" },
  { value: "Verizon Business", label: "Verizon Business" },
  {
    value: "Verlagsgruppe Georg von Holtzbrinck GmbH",
    label: "Verlagsgruppe Georg von Holtzbrinck GmbH",
  },
  { value: "versiko AG", label: "versiko AG" },
  { value: "Vestas Deutschland GmbH", label: "Vestas Deutschland GmbH" },
  {
    value: "Vetter Pharma-Fertigung GmbH & Co. KG",
    label: "Vetter Pharma-Fertigung GmbH & Co. KG",
  },
  { value: "VGH Versicherungen", label: "VGH Versicherungen" },
  {
    value: "VHV Allgemeine Versicherung AG",
    label: "VHV Allgemeine Versicherung AG",
  },
  { value: "VICTORIA Versicherung AG", label: "VICTORIA Versicherung AG" },
  { value: "Viega GmbH & Co. KG", label: "Viega GmbH & Co. KG" },
  {
    value: "Viessmann Werke GmbH & Co KG",
    label: "Viessmann Werke GmbH & Co KG",
  },
  { value: "Visteon Deutschland GmbH", label: "Visteon Deutschland GmbH" },
  { value: "Vodafone D2 GmbH", label: "Vodafone D2 GmbH" },
  { value: "Voith AG", label: "Voith AG" },
  { value: "Volkswagen AG", label: "Volkswagen AG" },
  { value: "Volkswagen Bank GmbH", label: "Volkswagen Bank GmbH" },
  { value: "Volkswagen Consulting", label: "Volkswagen Consulting" },
  { value: "Vorwerk & Co. KG", label: "Vorwerk & Co. KG" },
  { value: "VOSS Automotive GmbH", label: "VOSS Automotive GmbH" },
  { value: "VOSS Fluid GmbH + Co. KG", label: "VOSS Fluid GmbH + Co. KG" },
  { value: "VR-LEASING AG", label: "VR-LEASING AG" },
  {
    value: "VRG Vereinigte Rechenzentren GmbH",
    label: "VRG Vereinigte Rechenzentren GmbH",
  },
  { value: "WABCO GmbH & Co. OHG", label: "WABCO GmbH & Co. OHG" },
  { value: "Wacker-Chemie AG", label: "Wacker-Chemie AG" },
  { value: "WAGO Kontakttechnik GmbH", label: "WAGO Kontakttechnik GmbH" },
  { value: "Walhalla Fachverlag", label: "Walhalla Fachverlag" },
  {
    value: "Wandt Spedition Transportberatung GmbH",
    label: "Wandt Spedition Transportberatung GmbH",
  },
  {
    value: "WARSTEINER Brauerei Haus Cramer KG",
    label: "WARSTEINER Brauerei Haus Cramer KG",
  },
  { value: "Warth & Klein AG", label: "Warth & Klein AG" },
  {
    value: "Watson Wyatt Management Consultants",
    label: "Watson Wyatt Management Consultants",
  },
  {
    value: "WaveLight Laser Technologie AG",
    label: "WaveLight Laser Technologie AG",
  },
  { value: "WBI GmbH", label: "WBI GmbH" },
  { value: "Westdeutscher Rundfunk", label: "Westdeutscher Rundfunk" },
  { value: "WEB.DE GmbH", label: "WEB.DE GmbH" },
  { value: "Webasto AG", label: "Webasto AG" },
  {
    value: "Weber Shandwick Deutschland GmbH",
    label: "Weber Shandwick Deutschland GmbH",
  },
  { value: "Wehmeyer GmbH & Co KG", label: "Wehmeyer GmbH & Co KG" },
  { value: "WEISER, KUCK & COMP. GMBH", label: "WEISER, KUCK & COMP. GMBH" },
  { value: "WELEDA AG", label: "WELEDA AG" },
  { value: "Wella AG", label: "Wella AG" },
  {
    value: "Verlagsgruppe Weltbild GmbH",
    label: "Verlagsgruppe Weltbild GmbH",
  },
  { value: "WENDT GmbH", label: "WENDT GmbH" },
  {
    value: "Westdeutsche Genossenschafts-Zentralbank eG",
    label: "Westdeutsche Genossenschafts-Zentralbank eG",
  },
  {
    value: "Georg Westermann Verlag GmbH & Co. KG",
    label: "Georg Westermann Verlag GmbH & Co. KG",
  },
  { value: "Wiedenmann GmbH", label: "Wiedenmann GmbH" },
  { value: "Wieland-Werke AG", label: "Wieland-Werke AG" },
  { value: "WINGAS GmbH & Co. KG", label: "WINGAS GmbH & Co. KG" },
  { value: "WIRTSCHAFTSTREUHAND GMBH", label: "WIRTSCHAFTSTREUHAND GMBH" },
  { value: "Josef Witt GmbH", label: "Josef Witt GmbH" },
  { value: "Woco Industrietechnik GmbH", label: "Woco Industrietechnik GmbH" },
  { value: "Wolfsburg AG", label: "Wolfsburg AG" },
  {
    value: "Deutsche Woolworth GmbH & Co. OHG",
    label: "Deutsche Woolworth GmbH & Co. OHG",
  },
  { value: "Xenario GmbH", label: "Xenario GmbH" },
  { value: "Yahoo! Deutschland GmbH", label: "Yahoo! Deutschland GmbH" },
  {
    value: "Yamaha Motor Deutschland GmbH",
    label: "Yamaha Motor Deutschland GmbH",
  },
  {
    value: "Yamaha Music Central Europe GmbH",
    label: "Yamaha Music Central Europe GmbH",
  },
  { value: "Z-Systems AG", label: "Z-Systems AG" },
  {
    value: "Zweites Deutsches Fernsehen",
    label: "Zweites Deutsches Fernsehen",
  },
  { value: "Carl Zeiss AG", label: "Carl Zeiss AG" },
  {
    value: "Die Zeit - Zeitverlag Gerd Bucerius GmbH & Co. KG",
    label: "Die Zeit - Zeitverlag Gerd Bucerius GmbH & Co. KG",
  },
  {
    value: "Zeller+Gmelin GmbH & Co. KG",
    label: "Zeller+Gmelin GmbH & Co. KG",
  },
  { value: "ZF Friedrichshafen AG", label: "ZF Friedrichshafen AG" },
  { value: "ZF Sachs AG", label: "ZF Sachs AG" },
  { value: "Zollner Elektronik AG", label: "Zollner Elektronik AG" },
  { value: "ZWILLING J.A. HENCKELS AG", label: "ZWILLING J.A. HENCKELS AG" },
];
